"""add review table2

Revision ID: a398cd9f96f3
Revises: 939915d7e4ca
Create Date: 2025-11-05 00:17:04.109056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a398cd9f96f3'
down_revision: Union[str, None] = '939915d7e4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('reviews', 'reated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
